### PR TITLE
Sanha

### PR DESCRIPTION
**Pull request by headF1rst**

### CODE REVIEW

**Comment by headF1rst** [comment]
new dic

**Comment by LMS1229** [comment]
What is this directory? and Why create this folder??

**Comment by headF1rst** [comment]
Thats for my solution code and its explanations. Hope u authorize my commit. This dic will help my tuesday presentation  

나의 iPhone에서 보냄

**Comment by LMS1229** [comment]
Ok, However, it is not suitable for the purpose of the TLE group for personal use. Is it okay to arbitrarily adjust for public use?

**Pull request merged**
